<?php

namespace Database\Seeders;

use App\Models\Agent;
use Illuminate\Database\Seeder;

class AgentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Truncate existing agents
        Agent::truncate();

        $agents = [
            // ==========================================
            // TULUNGAGUNG REGION (BIRU / BLUE)
            // ==========================================
            [
                'code' => 'AGT-TA-01',
                'name' => 'Bambang Pamungkas',
                'city' => 'tulungagung',
                'district' => 'Tulungagung Kota',
                'village' => 'Kampungdalem',
                'type' => 'Tactical Lead',
                'status' => 'active',
                'latitude' => -8.0655,
                'longitude' => 111.9015,
                'signal_strength' => 98,
                'phone' => '0812-3344-5501',
                'description' => 'Koordinator Liputan Utama & Komando Lapangan Biro Tulungagung. Berjaga di Pusat Alun-Alun Tulungagung.',
            ],
            [
                'code' => 'AGT-TA-02',
                'name' => 'Agus Setiawan',
                'city' => 'tulungagung',
                'district' => 'Boyolangu',
                'village' => 'Serut',
                'type' => 'Field Reporter',
                'status' => 'patrol',
                'latitude' => -8.1150,
                'longitude' => 111.8980,
                'signal_strength' => 92,
                'phone' => '0812-3344-5502',
                'description' => 'Pemantauan lapangan kawasan cagar budaya dan destinasi wisata sejarah Candi Gayatri.',
            ],
            [
                'code' => 'AGT-TA-03',
                'name' => 'Siti Rahmawati',
                'city' => 'tulungagung',
                'district' => 'Kedungwaru',
                'village' => 'Rejoagung',
                'type' => 'Investigative Recon',
                'status' => 'active',
                'latitude' => -8.0450,
                'longitude' => 111.9210,
                'signal_strength' => 95,
                'phone' => '0813-7788-9903',
                'description' => 'Liputan investigasi sektor industri pabrik gula dan akses transportasi lingkar utara Tulungagung.',
            ],
            [
                'code' => 'AGT-TA-04',
                'name' => 'Hendra Wijaya',
                'city' => 'tulungagung',
                'district' => 'Ngunut',
                'village' => 'Kromasan',
                'type' => 'Traffic Patrol',
                'status' => 'patrol',
                'latitude' => -8.1100,
                'longitude' => 112.0120,
                'signal_strength' => 88,
                'phone' => '0857-1122-3304',
                'description' => 'Patroli lalu lintas dan perekonomian UMKM jalur arteri Tulungagung menuju Blitar.',
            ],
            [
                'code' => 'AGT-TA-05',
                'name' => 'Eko Prasetyo',
                'city' => 'tulungagung',
                'district' => 'Campurdarat',
                'village' => 'Gamping',
                'type' => 'Scout Drone',
                'status' => 'alert',
                'latitude' => -8.1720,
                'longitude' => 111.8540,
                'signal_strength' => 76,
                'phone' => '0858-4455-6605',
                'description' => 'Operasi drone udara pemantau aktivitas tambang marmer dan cuaca ekstrem perbukitan selatan.',
            ],
            [
                'code' => 'AGT-TA-06',
                'name' => 'Dian Lestari',
                'city' => 'tulungagung',
                'district' => 'Kauman',
                'village' => 'Bolorejo',
                'type' => 'Field Reporter',
                'status' => 'active',
                'latitude' => -8.0580,
                'longitude' => 111.8450,
                'signal_strength' => 90,
                'phone' => '0819-5566-7706',
                'description' => 'Peliputan sentra industri batik khas Tulungagung dan dinamika masyarakat agraris.',
            ],
            [
                'code' => 'AGT-TA-07',
                'name' => 'Budi Santoso',
                'city' => 'tulungagung',
                'district' => 'Besuki',
                'village' => 'Besole',
                'type' => 'Investigative Recon',
                'status' => 'standby',
                'latitude' => -8.2450,
                'longitude' => 111.7820,
                'signal_strength' => 82,
                'phone' => '0821-6677-8807',
                'description' => 'Monitoring kawasan pesisir Pantai Popoh, Sidem, dan mitigasi gelombang pasang selatan.',
            ],
            [
                'code' => 'AGT-TA-08',
                'name' => 'Rina Kurniawati',
                'city' => 'tulungagung',
                'district' => 'Sendang',
                'village' => 'Nglurup',
                'type' => 'Field Reporter',
                'status' => 'patrol',
                'latitude' => -7.9620,
                'longitude' => 111.8200,
                'signal_strength' => 85,
                'phone' => '0812-9900-1108',
                'description' => 'Peliputan lereng Gunung Wilis, perkebunan teh, dan pos pantau ekowisata agro.',
            ],
            [
                'code' => 'AGT-TA-09',
                'name' => 'Tri Wibowo',
                'city' => 'tulungagung',
                'district' => 'Gondang',
                'village' => 'Tiudan',
                'type' => 'Traffic Patrol',
                'status' => 'active',
                'latitude' => -8.0250,
                'longitude' => 111.8320,
                'signal_strength' => 94,
                'phone' => '0856-7788-9909',
                'description' => 'Pemantauan sentra kerajinan genteng dan rute perlintasan Tulungagung - Trenggalek.',
            ],

            // ==========================================
            // BLITAR REGION (MERAH / RED)
            // ==========================================
            [
                'code' => 'AGT-BL-01',
                'name' => 'Bayu Danendra',
                'city' => 'blitar',
                'district' => 'Kepanjenkidul',
                'village' => 'Bendo',
                'type' => 'Tactical Lead',
                'status' => 'active',
                'latitude' => -8.0920,
                'longitude' => 112.1620,
                'signal_strength' => 99,
                'phone' => '0812-4455-6610',
                'description' => 'Kepala Biro Radar Blitar. Pusat koordinasi Makam Bung Karno & Alun-Alun Kota Blitar.',
            ],
            [
                'code' => 'AGT-BL-02',
                'name' => 'Suryo Wicaksono',
                'city' => 'blitar',
                'district' => 'Sananwetan',
                'village' => 'Bendogerit',
                'type' => 'Field Reporter',
                'status' => 'active',
                'latitude' => -8.1020,
                'longitude' => 112.1810,
                'signal_strength' => 93,
                'phone' => '0813-8899-0011',
                'description' => 'Peliputan situs sejarah Monumen PETA dan aktivitas pemerintahan Kota Blitar.',
            ],
            [
                'code' => 'AGT-BL-03',
                'name' => 'Ratna Sari Dewi',
                'city' => 'blitar',
                'district' => 'Sukorejo',
                'village' => 'Pakunden',
                'type' => 'Investigative Recon',
                'status' => 'patrol',
                'latitude' => -8.1050,
                'longitude' => 112.1480,
                'signal_strength' => 89,
                'phone' => '0857-2233-4412',
                'description' => 'Observasi pergerakan logistik pasar legi dan simpul rel kereta api stasiun Blitar.',
            ],
            [
                'code' => 'AGT-BL-04',
                'name' => 'Gatot Sasongko',
                'city' => 'blitar',
                'district' => 'Kanigoro',
                'village' => 'Satreyan',
                'type' => 'Traffic Patrol',
                'status' => 'active',
                'latitude' => -8.1320,
                'longitude' => 112.2180,
                'signal_strength' => 96,
                'phone' => '0858-5566-7713',
                'description' => 'Pengawasan pusat pemerintahan Kantor Bupati Blitar Baru di Kanigoro.',
            ],
            [
                'code' => 'AGT-BL-05',
                'name' => 'Arif Hidayat',
                'city' => 'blitar',
                'district' => 'Wlingi',
                'village' => 'Beru',
                'type' => 'Field Reporter',
                'status' => 'alert',
                'latitude' => -8.0850,
                'longitude' => 112.3180,
                'signal_strength' => 78,
                'phone' => '0819-6677-8814',
                'description' => 'Laporan lapangan kawasan lereng Gunung Kelud timur dan sentra peternakan sapi perah.',
            ],
            [
                'code' => 'AGT-BL-06',
                'name' => 'Maya Anggraini',
                'city' => 'blitar',
                'district' => 'Srengat',
                'village' => 'Dandong',
                'type' => 'Scout Drone',
                'status' => 'patrol',
                'latitude' => -8.0620,
                'longitude' => 112.0620,
                'signal_strength' => 91,
                'phone' => '0821-7788-9915',
                'description' => 'Patroli drone tapal batas Blitar-Kediri dan kelancaran jembatan penyeberangan Sungai Brantas.',
            ],
            [
                'code' => 'AGT-BL-07',
                'name' => 'Dimas Pratama',
                'city' => 'blitar',
                'district' => 'Garum',
                'village' => 'Tawangsari',
                'type' => 'Field Reporter',
                'status' => 'active',
                'latitude' => -8.0750,
                'longitude' => 112.2280,
                'signal_strength' => 87,
                'phone' => '0812-1122-3316',
                'description' => 'Liputan perayaan budaya dan cagar budaya Candi Penataran di jalur utara Garum-Nglegok.',
            ],
            [
                'code' => 'AGT-BL-08',
                'name' => 'Anita Kusuma',
                'city' => 'blitar',
                'district' => 'Sutojayan',
                'village' => 'Kalipang',
                'type' => 'Investigative Recon',
                'status' => 'standby',
                'latitude' => -8.1850,
                'longitude' => 112.2150,
                'signal_strength' => 84,
                'phone' => '0856-3344-5517',
                'description' => 'Pos pantau wilayah Blitar Selatan, bendungan Lodoyo, dan mitigasi luapan DAS Brantas.',
            ],
            [
                'code' => 'AGT-BL-09',
                'name' => 'Fajar Nugroho',
                'city' => 'blitar',
                'district' => 'Nglegok',
                'village' => 'Modangan',
                'type' => 'Scout Drone',
                'status' => 'active',
                'latitude' => -8.0120,
                'longitude' => 112.2020,
                'signal_strength' => 92,
                'phone' => '0813-5566-7718',
                'description' => 'Pemantauan aktivitas vulkanik Gunung Kelud dan perkebunan kopi Karanganyar.',
            ],

            // ==========================================
            // TRENGGALEK REGION (KUNING / YELLOW)
            // ==========================================
            [
                'code' => 'AGT-TG-01',
                'name' => 'Wahyu Hidayat',
                'city' => 'trenggalek',
                'district' => 'Trenggalek Kota',
                'village' => 'Surodakan',
                'type' => 'Tactical Lead',
                'status' => 'active',
                'latitude' => -8.0550,
                'longitude' => 111.7120,
                'signal_strength' => 97,
                'phone' => '0812-7788-9919',
                'description' => 'Koordinator Liputan Wilayah Trenggalek. Pusat operasional di Alun-Alun dan Pendopo Trenggalek.',
            ],
            [
                'code' => 'AGT-TG-02',
                'name' => 'Joko Susilo',
                'city' => 'trenggalek',
                'district' => 'Watulimo',
                'village' => 'Tasikmadu',
                'type' => 'Field Reporter',
                'status' => 'patrol',
                'latitude' => -8.2650,
                'longitude' => 111.7280,
                'signal_strength' => 86,
                'phone' => '0813-2233-4420',
                'description' => 'Liputan maritim Pelabuhan Perikanan Nusantara Prigi dan kawasan Pantai Pasir Putih.',
            ],
            [
                'code' => 'AGT-TG-03',
                'name' => 'Sri Wahyuni',
                'city' => 'trenggalek',
                'district' => 'Durenan',
                'village' => 'Semen',
                'type' => 'Traffic Patrol',
                'status' => 'active',
                'latitude' => -8.0920,
                'longitude' => 111.7920,
                'signal_strength' => 94,
                'phone' => '0857-6677-8821',
                'description' => 'Pemantauan simpul persimpangan perbatasan Trenggalek - Tulungagung di Durenan.',
            ],
            [
                'code' => 'AGT-TG-04',
                'name' => 'Ilham Ramadhan',
                'city' => 'trenggalek',
                'district' => 'Karangan',
                'village' => 'Sumberingin',
                'type' => 'Investigative Recon',
                'status' => 'active',
                'latitude' => -8.0880,
                'longitude' => 111.6680,
                'signal_strength' => 91,
                'phone' => '0858-9900-1122',
                'description' => 'Investigasi komoditas perkebunan kakao, durian, dan sentra olahan keripik tempe khas.',
            ],
            [
                'code' => 'AGT-TG-05',
                'name' => 'Putri Ayu',
                'city' => 'trenggalek',
                'district' => 'Panggul',
                'village' => 'Wonocoyo',
                'type' => 'Field Reporter',
                'status' => 'alert',
                'latitude' => -8.2420,
                'longitude' => 111.4550,
                'signal_strength' => 74,
                'phone' => '0819-3344-5523',
                'description' => 'Peliputan konservasi penyu Pantai Pelang dan pemukiman pesisir ujung barat Trenggalek.',
            ],
            [
                'code' => 'AGT-TG-06',
                'name' => 'Bagus Saputra',
                'city' => 'trenggalek',
                'district' => 'Gandusari',
                'village' => 'Sukorejo',
                'type' => 'Scout Drone',
                'status' => 'patrol',
                'latitude' => -8.0820,
                'longitude' => 111.6320,
                'signal_strength' => 88,
                'phone' => '0821-4455-6624',
                'description' => 'Patroli jalur perbukitan dan pemantauan titik rawan tanah gerak di lereng barat.',
            ],
            [
                'code' => 'AGT-TG-07',
                'name' => 'Nanda Safitri',
                'city' => 'trenggalek',
                'district' => 'Pogalan',
                'village' => 'Ngadirenggo',
                'type' => 'Field Reporter',
                'status' => 'active',
                'latitude' => -8.0650,
                'longitude' => 111.7580,
                'signal_strength' => 93,
                'phone' => '0812-8899-0025',
                'description' => 'Liputan desa wisata agrikultur dan pemantauan DAS Sungai Ngasinan Trenggalek.',
            ],
            [
                'code' => 'AGT-TG-08',
                'name' => 'Doni Prasetya',
                'city' => 'trenggalek',
                'district' => 'Tugu',
                'village' => 'Prambon',
                'type' => 'Investigative Recon',
                'status' => 'standby',
                'latitude' => -8.0250,
                'longitude' => 111.6420,
                'signal_strength' => 85,
                'phone' => '0856-1122-3326',
                'description' => 'Pemantauan konstruksi infrastruktur Bendungan Tugu dan jalur penghubung Trenggalek - Ponorogo.',
            ],
            [
                'code' => 'AGT-TG-09',
                'name' => 'Lestari Handayani',
                'city' => 'trenggalek',
                'district' => 'Bendungan',
                'village' => 'Masaran',
                'type' => 'Scout Drone',
                'status' => 'active',
                'latitude' => -7.9750,
                'longitude' => 111.7050,
                'signal_strength' => 89,
                'phone' => '0813-6677-8827',
                'description' => 'Perekaman elevasi udara kawasan hutan lindung Wilis Selatan dan agrowisata Dilem Wilis.',
            ],
        ];

        foreach ($agents as $agentData) {
            Agent::create($agentData);
        }
    }
}
